# Generated by Django 4.2.1 on 2023-10-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0003_todo_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='add_date',
            new_name='added_date',
        ),
    ]
